image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential
- rustc --version && cargo --version

test:
  script:
  - cargo test --locked --all --jobs 1 -- --nocapture
  - cargo test --benches --locked --all --jobs 1
  - cd fuzz && cargo check --locked

aarch64:
  variables:
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER: qemu-aarch64-static -L /usr/aarch64-linux-gnu
  script:
  - rustup target add aarch64-unknown-linux-gnu
  - apt-get install -yqq gcc-aarch64-linux-gnu qemu-user-static
  - cargo test --target aarch64-unknown-linux-gnu --locked --all --jobs 1

freebsd:
  script:
  - rustup target add x86_64-unknown-freebsd
  - cargo check --target x86_64-unknown-freebsd --locked --all --tests --jobs 1

fmt:
  allow_failure: true
  script:
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cd fuzz && cargo fmt -- --check
