image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential
- rustc --version && cargo --version

test:
  variables:
    RUSTUP_TOOLCHAIN: nightly-2019-05-08
  script:
  - cargo test --locked --all --verbose --jobs 1 -- --nocapture
  - cargo test --locked --all --verbose --jobs 1 --features=bench -- --nocapture

fmt:
  allow_failure: true
  variables:
    RUSTUP_TOOLCHAIN: nightly-2019-05-08
  script:
  - rustup component add rustfmt
  - cargo fmt -- --check
