name: CI

on:
  push:
    branches:
      - trying
      - staging

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.54.0
        default: true
        profile: minimal
        components: rustfmt, clippy

    - uses: actions/setup-node@v2
      if: matrix.os == 'windows-latest'
      with:
        node-version: '16'

    - uses: Swatinem/rust-cache@v1

    - name: Clippy
      run: cargo clippy --all --all-targets -- -D clippy::all

    - name: Test (ubuntu/macos)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      env:
        CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: sudo -E
        CARGO_TARGET_X86_64_APPLE_DARWIN_RUNNER: sudo -E
        RUSTFLAGS: -D warnings
      run: cargo test --all --all-targets --all-features --locked

    - name: Cache node_modules (windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-modules-

    - name: Test (windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      env:
        RUSTFLAGS: -D warnings
        TESTING: 1
      run: |
        set -ex
        cd windows-gui-client && yarn && yarn build && cd ..
        cargo test --all --all-targets --locked

    - name: Fmt check
      if: matrix.os == 'macos-latest'
      run: |
        set -ex
        cargo fmt --all -- --check
        cd tools/check-copyright && cargo fmt -- --check && cargo build --release && cd ../..
        ./tools/check-copyright/target/release/check-copyright
        cd fuzz && cargo fmt -- --check

  # Make CI a bit faster running these in parallel with other tests.
  integration-test-and-check-fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal

    - name: Integration Test
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get install -yqq wireguard net-tools
        cargo build
        cd ns-test
        sudo ./integration-test.sh
        sudo ./interop-test.sh

    - name: Check Fuzz
      run: cd fuzz && cargo check --locked
